myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pizzasystem.urls')),
    path('admin/', admin.site.urls),
]

pizzasystem/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('order/', views.pizza_order, name='order'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirmation/<int:order_id>/', views.confirmation, name='confirmation'),
    path('login_user/', views.login_user, name='login'),
    path('register_user/', views.register_user, name='register_user'),
    path('logout/', views.logout_user, name='logout'),
    path('list_orders/', views.list_orders, name='list_orders'),
]

pizzasystem/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.TextField()
    address = models.TextField()
    credit_card_number = models.CharField(max_length=16, null=True, blank=True)
    credit_card_expiry = models.CharField(max_length=5, null=True, blank=True) 
    credit_card_cvv = models.CharField(max_length=4, null=True, blank=True)
    email = models.EmailField()
    


    def clean(self):
        super().clean()
        # Validate credit card number with Luhn Algorithm
        if self.credit_card_number and not UserProfile.luhn_check(self.credit_card_number):
            raise ValidationError("Invalid credit card number.")
        
        # Validate CVV
        if self.credit_card_cvv and not UserProfile.is_valid_cvv(self.credit_card_cvv):
            raise ValidationError("Invalid CVV. CVV must be 3 or 4 digits long.")
        
    @staticmethod
    def luhn_check(card_number):
        if (card_number.isdigit() and len(card_number) == 16):
            return True
    
    @staticmethod
    def is_valid_cvv(cvv):
        return cvv.isdigit() and len(cvv) in [3, 4]
    
    
#choices for pizza
class Pizza(models.Model):
    SIZE_CHOICES = [
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
    ]
    CRUST_CHOICES = [
        ('N', 'Normal'),
        ('TH', 'Thick'),
        ('TN', 'Thin'),
        ('GF', 'Gluten Free'),
    ]
    
    SAUCE_CHOICES = [
        ('TOM', 'Tomato'),
        ('BBQ', 'BBQ'),
    ]
    CHEESE_CHOICES = [
        ('MOZ', 'Mozzarella'),
        ('VEG', 'Vegan'),
        ('LF', 'Low Fat'),
    ]
    
    TOPPING_CHOICES = [
    ('Pepperoni', 'Pepperoni'),
    ('Chicken', 'Chicken'),
    ('Ham', 'Ham'),
    ('Pineapple', 'Pineapple'),
    ('Peppers', 'Peppers'),
    ('Mushrooms', 'Mushrooms'),
    ('Onions', 'Onions'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    size = models.CharField(max_length=1, choices=SIZE_CHOICES, default='S')
    crust = models.CharField(max_length=2, choices=CRUST_CHOICES, default='N')
    sauce = models.CharField(max_length=3, choices=SAUCE_CHOICES, default='TOM')
    cheese = models.CharField(max_length=3, choices=CHEESE_CHOICES, default='MOZ')
    toppings = models.CharField(max_length=15, choices=TOPPING_CHOICES, default='Pepperoni')
    order_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.get_size_display()} {self.get_toppings_display()} Pizza ordered by {self.user.userprofile.name}"

pizzasystem/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class PizzaForm(forms.ModelForm):

    class Meta:
        model = Pizza
        fields = ['size', 'crust', 'sauce', 'cheese', 'toppings']
        
        
    
        
class Checkout(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'address', 'credit_card_number', 'credit_card_expiry', 'credit_card_cvv', 'email']  # Corrected 'paymentinfo'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'small-input'}),
            'address': forms.TextInput(attrs={'class': 'small-input'}),
        }

pizzasystem/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import PizzaForm
from .forms import Checkout
from django.utils.timezone import now 
from .models import UserProfile, Pizza
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm



def index(request):
    return render(request, 'index.html')

@login_required
def pizza_order(request):
    if request.method == 'POST':
        form = PizzaForm(request.POST)
        if form.is_valid():
            pizza_order = form.save(commit=False)
            pizza_order.user = request.user
            pizza_order.save()
            request.session['order_id'] = pizza_order.id #each pizza object has a unique id
            
            return redirect('checkout') 
    else:
        form = PizzaForm()
    return render(request, 'order.html', {'form':form})

@login_required
def checkout(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)
    
    if request.method == 'POST':
        form = Checkout(request.POST, instance=user_profile) 
        if form.is_valid():
            form.save()
            return redirect('confirmation', order_id=request.session['order_id'])
        else:
            print(form.errors) 
    else:
        form = Checkout(instance=user_profile)
    return render(request, 'checkout.html', {'form': form})

@login_required
def confirmation(request, order_id):
    order_id = request.session.get('order_id')
    order = Pizza.objects.get(id=order_id, user=request.user)

    return render(request, 'confirmation.html', {'order': order})

def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			messages.success(request, f'Hi, {user.username}!')
			return redirect('index')
		
		else:
			messages.success(request, ("There Was An Error Logging In, Try Again..."))	
			return redirect('login')	

	else:
		return render(request, 'registration/login.html', {})

def logout_user(request):
	logout(request)
	messages.success(request, ("You Were Logged Out!"))
	return redirect('index')


def register_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  
            messages.success(request, "Registration successful!")
            return redirect('index')  # Redirect to a success or home page
        else:
            messages.error(request, "Unsuccessful registration. Invalid information.")
    else:
        form = UserCreationForm()
    return render(request, 'registration/register_user.html', {'form': form})

@login_required
def list_orders(request):
    # Fetch all pizza orders for the logged-in user
    orders = Pizza.objects.filter(user=request.user).order_by('-order_date')
    return render(request, 'list-out.html', {'orders': orders})

pizzasystem/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Default Title{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav>
        <ul class="navbar-list">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'order' %}">Order</a></li>
            <li><a href="{% url 'checkout' %}">Checkout</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'register_user' %}">Register</a></li>
            <li><a href="{% url 'list_orders' %}">List of Orders</a></li>
        </ul>
    </nav>
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
</body>
</html>

pizzasystem/templates/checkout.html
{% extends 'base.html' %}

{% block title %}Checkout{% endblock %}
{% block content %}
<h2>Thank you for your order!</h2>

<div class="form-container">
    <h2>Add your details</h2>
    <form method="post" action="{% url 'checkout' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Submit Order</button>
    </form>
</div>
{% endblock %}

pizzasystem/templates/confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Order Confirmation
{% endblock %}

{% block content %}
    <h2>Thank you, {{ request.user.username }}!</h2>
    <p>You ordered: A {{ order.get_size_display }} {{ order.get_crust_display }} crust {{ order.get_toppings_display}} pizza with {{ order.get_sauce_display }} sauce and {{ order.get_cheese_display }} cheese.</p>
    
    <div class="confirmation_container">
        <h2>Order Details:</h2>
        <ul>
            <li>Size: {{ order.get_size_display }}</li><br>
            <li>Crust: {{ order.get_crust_display }}</li><br>
            <li>Sauce: {{ order.get_sauce_display }}</li><br>
            <li>Cheese: {{ order.get_cheese_display }}</li><br>
            <li>Toppings: {{ order.get_toppings_display }}</li><br>
            <li>Ordered on: {{ order.order_date|date:"F d, Y H:i" }}</li><br>
        </ul>
    </div>

    <p>If you have any questions about your order, please contact us.</p>
{% endblock %}
{% block footer %}
<footer class="footer">
    Copyright Faith Njekwe
</footer>
{% endblock %}

pizzasystem/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	Pizza Website
{% endblock %}

{% block content %}
    <h2> Welcome customer, what would you like to order?</h2>
	<div class="content-container">
		<div id="pizza-image">
		<img src="{% static 'images/pizza-image2.jpg' %}" alt="Pizza 2">
		<br>
		<br>
		<a href="{% url 'login' %}" class="button-index">Login!</a>
		</div>
	</div>
{% endblock %}
{% block footer %}
<footer class="footer">
    Copyright Faith Njekwe
</footer>
{% endblock %}

pizzasystem/templates/list-out.html
{% extends "base.html" %}

{% block title %}Your Orders{% endblock %}

{% block content %}
<h2>Hi {{ request.user.username }},</h2>
<div class="list_out_container">
    {% if orders %}
        <ul>
        {% for order in orders %}
            <li> {{forloop.counter}}. {{ order.get_size_display }} {{ order.get_crust_display }} Crust {{ order.get_sauce_display }} Sauce Pizza with {{ order.get_cheese_display }} and {{ order.get_toppings_display }}.<li>
            <br><br>
            <li>Ordered on: {{ order.order_date|date:"F d, Y H:i" }}</li><br>
        {% endfor %}
        </ul>
    {% else %}
        <p>You have no orders yet.</p>
    {% endif %}
</div>
{% endblock %}

pizzasystem/templates/order.html
{% extends 'base.html' %}

{% block title %}
    Order Your Pizza        
{% endblock %}

{% block content %}
<h2>What would you like to order?<h2>

<div class="form-container">
    <form method="post" action="{% url 'order' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Submit Order</button>
    </form>
</div>
{% endblock %}
<!-- Footer -->
<footer class="text-white text-center py-3" style="background-color: #ff0000;"> <!-- Inline style for custom red color -->
    <div class="container">
        <span>© Faith Njekwe</span>
    </div>
</footer>
<!-- End of Footer -->